apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-sa
---
apiVersion: v1
kind: Pod
metadata:
  name: sa-demo
spec:
  serviceAccountName: custom-sa
  containers:
    - name: app
      image: busybox
      command: ['sleep', '3600']